### PR TITLE
Enhanced iframe id assignment

### PR DESCRIPTION
**Pull request by mthieleguj**
Get „iframeId“ from data-attribute of the iframe element in which the script is embedded

### CODE REVIEW

**Comment by jfmaeck** [comment]
Hi @mthieleguj, thank you for your pull request.

Please correct me if I am wrong, but I am pretty sure that this won't work with cross domain iframes. A more robust approach would probably be to post the preset iframe id from the parent to the child using window.postMessage, as it is done with the deepLink:changed event:

set-iframe-height-parent.js:

``` js
        if (iframe.contentWindow && iframe.contentWindow.postMessage) {
          iframe.contentWindow.postMessage('setIframeHeight:deepLink:changed::{ "parentUrl": "'+parentUrl+'", "childUrl": "'+data.iframeSrc+'"}', '*');
        }
```

set-iframe-height-child.js:

``` js
...
          switch (eventName) {
            case 'setIframeHeight:deepLink:changed':
              $(window).trigger('setIframeHeight:deepLink:changed', params);
              break;
          }
...
```

Just out of curiosity: May I ask why you need to define your own static iframe ids?

Cheers,

Jonas

**Comment by mthieleguj** [comment]
Hi Jonas,

we're embedding external widget codes in dynamically created iframes on the same domain with `src="about:blank"`

e.g.:

 `<iframe src="about:blank">`

 `<!DOCTYPE html><html><head></head><body>[widget code]<script src="set-iframe-height-child.js"></script></body></html>`

 `</iframe>`

The functions "findIframeById" and "findIframeBySrc" don't work with `src="about:blank"`, so defining a static id seems to be a practical solution... if we are on the same domain.

Regards,

Martin

**Comment by jfmaeck** [comment]
Hi Martin,

OK, sounds like a reasonable feature. Could you please wrap the `self.frameElement.getAttribute` part of your change in a try catch block to avoid errors in cross domain situations?
And a simple example within the `demo` folder as well as perhaps a short note in the `README.md` would be perfect.

Thank you!

Jonas

**Comment by jfmaeck** [comment]
Sorry for merging late, I must have missed your last commit. Thanks for that, good job!

**Comment by mthieleguj** [comment]
No problem, thanks.

**Pull request merged**
